//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class 学生表
    {
        public string 学号 { get; set; }
        public string 姓名 { get; set; }
        public string 性别 { get; set; }
        public string 班级 { get; set; }
        public string 通信地址 { get; set; }
        public Nullable<System.DateTime> 出生日期 { get; set; }
        public Nullable<decimal> 身高 { get; set; }
        public string 密码 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
    
        public virtual 班级表 班级表 { get; set; }
    }
}
