//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class 学生名单
    {
        public string 身份证号 { get; set; }
        public string 姓名 { get; set; }
        public string 性别 { get; set; }
        public string 民族 { get; set; }
        public string 年级 { get; set; }
        public string 入学年月 { get; set; }
        public string 招生类型 { get; set; }
        public string 班级 { get; set; }
        public string 学制 { get; set; }
        public string 班级1 { get; set; }
        public string 联招合作类型 { get; set; }
        public string 联招合作学校机构代码 { get; set; }
        public string 户籍所在省 { get; set; }
        public string 户籍所在市 { get; set; }
        public string 户籍所在区县 { get; set; }
        public string 详细地址 { get; set; }
        public string 户籍性质 { get; set; }
        public string 是否低保 { get; set; }
        public string 是否享受国家助学金 { get; set; }
        public string 助学金月发放标准_元_ { get; set; }
        public string 学生类型 { get; set; }
        public string 生源类别 { get; set; }
        public string 家长_监护人_姓名 { get; set; }
        public string 家长_监护人_电话 { get; set; }
        public string 学习形式 { get; set; }
        public string 学生类别 { get; set; }
        public string 出生日期 { get; set; }
        public string 校内学号 { get; set; }
        public string 联系电话 { get; set; }
        public string 邮政编码 { get; set; }
        public string 省级电子注册学籍号 { get; set; }
        public string 曾用名 { get; set; }
        public string 政治面貌 { get; set; }
        public string 籍贯 { get; set; }
        public string 港澳台侨胞 { get; set; }
        public string 毕业学校 { get; set; }
        public string 现家庭住址 { get; set; }
        public string 电子邮箱 { get; set; }
        public string 银行卡号 { get; set; }
        public string 备注 { get; set; }
        public Nullable<double> 金额 { get; set; }
    }
}
